/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.4/userguide/building_swift_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
val universityFolder = ":computer-science:tasks:"
pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}

rootProject.name = "sba-modules"
include(
    "app", "list", "utilities", "abs-app", "core-app", "auth-server", "auth-server-webflux",
    "authorization-server-oauth2", "resource-server-jwe")
include (
    universityFolder.plus("StringBuilderNotifier"),
    universityFolder.plus("StringBuilderUndo"),
    universityFolder.plus("TemperatureConverter"),
    universityFolder.plus("FinalControlWork"),
    universityFolder.plus("ThreadState")
)
